version: '3'

services:
  backend:
    image: server
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/code
    command: python3 -m server
    ports:
      - '5010:5000'
    working_dir: /code
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./frontend/dist/:/www/data/
  #   ports:
  #     - '80:80'
  #     - '5020:80'