version: '2'

services:
  backend:
    image: server
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/code
    command: python3 -m app
    ports:
      - '5020:5030'
    working_dir: /code
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/:/www/data/
      - ./https/:/etc/nginx/conf.d/https
    links:
      - backend
    ports:
      - '443:443'
      - '80:80'
      