const ImageArray = {
  'en': [
    'mo_en_2',
    'mo_en_3',
    'mo_en_4',
    'mo_en_5',
    'mo_en_6',
    'mo_en_7',
    'mo_en_8',
    'mo_en_9',
    'mo_en_10',
    'mo_en_11',
    'mo_en_12',
    'mo_en_13',
    'mo_en_14',
    'mo_en_15',
    'mo_en_16',
    'mo_en_17',
    'mo_en_18',
    'mo_en_19',
    'mo_en_20',
    'mo_en_21',
    'mo_en_22',
    'mo_en_23',
    'mo_en_24',
    'mo_en_25',
    'mo_en_26',
    'mo_en_27',
    'mo_en_28',
    'mo_en_29',
    'mo_en_30',
    'mo_en_31',
    'mo_en_32',
    'mo_en_33',
    'mo_en_34',
    'mo_en_35',
    'mo_en_36',
    'mo_en_37',
    'mo_en_38',
    'mo_en_39',
    'mo_en_40'
  ],
  'zh': [
    'mo_zh_2',
    'mo_zh_3',
    'mo_zh_4',
    'mo_zh_5',
    'mo_zh_6',
    'mo_zh_7',
    'mo_zh_8',
    'mo_zh_9',
    'mo_zh_10',
    'mo_zh_11',
    'mo_zh_12',
    'mo_zh_13',
    'mo_zh_14',
    'mo_zh_15',
    'mo_zh_16',
    'mo_zh_17',
    'mo_zh_18',
    'mo_zh_19',
    'mo_zh_20',
    'mo_zh_21',
    'mo_zh_22',
    'mo_zh_23',
    'mo_zh_24',
    'mo_zh_25',
    'mo_zh_26',
    'mo_zh_27',
    'mo_zh_28',
    'mo_zh_29',
    'mo_zh_30',
    'mo_zh_31',
    'mo_zh_32',
    'mo_zh_33',
    'mo_zh_34',
    'mo_zh_35',
    'mo_zh_36',
    'mo_zh_37'
  ]
}

const videoList = {
  'zh_34': 'http://images.shinemeditation.cn/video/mp4/bottom_left.mp4bottom_left.mp4',
  'zh_35': 'http://images.shinemeditation.cn/video/mp4/bottom_right.mp4bottom_right.mp4',
  'en_36': 'http://images.shinemeditation.cn/video/mp4/bottom_left.mp4bottom_left.mp4',
  'en_37': 'http://images.shinemeditation.cn/video/mp4/bottom_right.mp4bottom_right.mp4'
}

export {
  ImageArray,
  videoList
}
